### ISSUE TITLE
Issue finding the geolocation of the ID's

### ISSUE THREAD

**Issue by pandugorthi** [MilaNLProc/twitter-demographer#4]
Python Version :3:10
OS: Windows 11

Description:
I used the code provided as a testrun, with only changing the Tweet ids. I ran into two issues with the sample code.
1. When executing the sample code - I received an error that the "NameError: name 'GeoNamesDecoder' is not defined". Should I define the component separately? 
2. When re-hydrating the ids I did not receive any information. All the columns were null values in the dataframe.
Am I missing something in the code?

Code:

from twitter_demographer.twitter_demographer import Demographer
from twitter_demographer.components import Rehydrate
from twitter_demographer.demographics.m3 import GenderAndAge
import pandas as pd

BEARER_TOKEN="########"
GEONAMES_TOKEN="####"

demo = Demographer()

data = pd.DataFrame({"tweet_ids": ["1470045456986170000", "1470254428334830000", "1472170336401690000", "1470987007971280000", "1472034701623890000"]})

component_one = Rehydrate(BEARER_TOKEN)
component_two = GeoNamesDecoder(GEONAMES_TOKEN)
component_three = HuggingFaceClassifier("cardiffnlp/twitter-roberta-base-sentiment")

demo.add_component(component_one)
#demo.add_component(component_two)
#demo.add_component(component_three)

d1=demo.infer(data)

Error 1: 
component_two = GeoNamesDecoder(GEONAMES_TOKEN)
Traceback (most recent call last):

  File "<ipython-input-26-a410b13d860e>", line 1, in <module>
    component_two = GeoNamesDecoder(GEONAMES_TOKEN)

NameError: name 'GeoNamesDecoder' is not defined

Error 2: 

I attached the images of the data and the rehydrated data
![data](https://user-images.githubusercontent.com/14245066/154630832-dc86390d-188e-4538-bfc3-bb7f2b0a9bf4.png)
![image](https://user-images.githubusercontent.com/14245066/154630932-06393684-e8d6-4e96-be64-ed436b2c6697.png)

Thank you in advance for all your help.

**Comment by vinid** [comment]
Hello!

**GeoNames**

You need to import the geonames decoder:

```python

from twitter_demographer.geolocation.geonames import GeoNamesDecoder
```

**for the reconstruction error:**

the tweet ids you are using do not seem to be valid. You can see that they all have "0000" at the end. Have you opened these with excel or something like that? this issue usually comes from the fact that excel interprets those numbers as integers and transforms those in exponential notation that is then transformed back into those numbers with 0000 at the end

You can see that this tweet [https://twitter.com/user/status/1470045456986170000](https://twitter.com/user/status/1470045456986170000) does not exist. Instead, this is a valid tweet id [https://twitter.com/user/status/1477976329710673921](https://twitter.com/user/status/1477976329710673921)

Let me know if this helps :)

**Comment by pandugorthi** [comment]
Hi 

Thank you!!. got it. I did not realize that excel is messing with the id's .
