### ISSUE TITLE
Error when importing HuggingFaceClassifier

### ISSUE THREAD

**Issue by ggkioka** [MilaNLProc/twitter-demographer#5]
* Twitter Demographer version: twitter-demographer 0.1.6 (installed with pip)
* Python version: 3.8
* Operating System: MacOS Big Sur

### Description

I was trying to import the following command on Colab and locally on MacOS.
from twitter_demographer.classification.transformers import HuggingFaceClassifier

### The following error appeared

```
module 'datasets' has no attribute 'set_progress_bar_enabled'
```
Could you please check?

**Comment by vinid** [comment]
Hello @ggkioka,

I am taking a look now!

**Comment by vinid** [comment]
A recent update in the datasets library is causing this error. See [this](https://github.com/huggingface/datasets/issues/4085). For a quick fix, you can downgrade the datasets library.

Anyway, I'll fix this and deploy a new version of the package by the end of the day.

**Comment by vinid** [comment]
should be up fixed :)
